### ISSUE TITLE
[Question] How do I add banners to a banner rack with banners and does the banner rack accept multiple banners of the same type?

### ISSUE THREAD

**Issue by vavavr00m** [JavidPack/BannerBonanza#12]
I've been having issues where:
1. I couldn't add more banners to a rack after the initial addition
2. Adding to a banner rack doesn't add all the banners in my inventory. I've already built more than 10 and we struggle to figure out how to add all the banners in a single rack.

Is there a limit to the number of banners? If none, how?

Additionally, does the banner rack accept multiple banners of the same type?

**Comment by JavidPack** [comment]
You can only put 1 of a specific banner into it. There is no reason to have multiple of the same banner added, that doesn't affect anything.

If unique banners from your inventory aren't going in, they might be incorrectly programmed or are banner tiles that don't provide buffs, like some of the dungeon ones.

Right clicking once is all you need to do to move all the banners that can be used

**Comment by vavavr00m** [comment]
Thank you so much for clarifying!
