### ISSUE TITLE
GRealm's banners cause a divide by zero error when placed in the Banner Rack

### ISSUE THREAD

**Issue by AJMJ2012** [JavidPack/BannerBonanza#2]
> Silently Caught Exception: Attempted to divide by zero.   at BannerBonanza.Tiles.BannerRackTile.SpecialDraw(Int32 i, Int32 j, SpriteBatch spriteBatch) in D:\Documents\My Games\Terraria/ModLoader\Mod Sources\BannerBonanza\Tiles\BannerRackTile.cs:line 124

There isn't much more that I can explain about this.

**Comment by JavidPack** [comment]
thanks. It's likely Grealms fault, they have very funky banner code, but I'll see if I can figure out why next time I work on this mod.
