### ISSUE TITLE
Banner Rack MP Map Crash 

### ISSUE THREAD

**Issue by TheBambino** [JavidPack/BannerBonanza#3]
While in multiplayer, having your map open, and hovering your mouse over a banner rack, a crash occurs 100% of the time. However, if the chunk that contains the banner rack is already loaded for the player, it will not occur.

[client.log](https://github.com/JavidPack/BannerBonanza/files/6951593/client.log)

**Comment by JavidPack** [comment]
Thanks for the report.

**Comment by JavidPack** [comment]
Should be fixed.
